# Fixed Deposit Account Rules
tenure.bucket.new=0
tenure.bucket.standard=1
tenure.bucket.premium=3
tenure.bucket.privilege=5

interest.rate.short=5.00
interest.rate.medium=6.50
interest.rate.long=7.50

daily.transfer.limit.new=0
daily.transfer.limit.standard=0
daily.transfer.limit.premium=0
daily.transfer.limit.privilege=0
